services:
  app:
    build: .
    container_name: jazda-app
    environment:
      APP_ENV: production
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      APP_TIMEZONE: ${APP_TIMEZONE}
    ports:
      - "127.0.0.1:8082:80"
    volumes:
      - ./server/storage:/var/www/server/storage
    restart: unless-stopped
